export type PlaceCategory = "basis" | "ruhe" | "gruen" | "sehen" | "essen" | "kaffee" | "shoppen" | "gp";

export type Place = {
  id: string;
  name: string;
  kicker: string;
  category: PlaceCategory;
  lat: number;
  lng: number;
  address: string;
  hours: string;
  price: string;
  quiet: 1 | 2 | 3 | 4 | 5;
  bestTime: string;
  description: string;
  note?: string;
  tags: string[];
  source: string;
};

export const categoryMeta: Record<PlaceCategory, { label: string; color: string; icon: string }> = {
  basis: { label: "Basis", color: "#1b7785", icon: "⌂" },
  ruhe: { label: "Rückzug", color: "#7357a4", icon: "◌" },
  gruen: { label: "Grün", color: "#417b5a", icon: "♧" },
  sehen: { label: "Ansehen", color: "#2f6bb2", icon: "✦" },
  essen: { label: "Essen", color: "#d35f35", icon: "◇" },
  kaffee: { label: "Café", color: "#9b6b3b", icon: "○" },
  shoppen: { label: "Vintage-Kleidung", color: "#b7487d", icon: "♢" },
  gp: { label: "GP", color: "#db2737", icon: "▰" },
};

export const places: Place[] = [
  {
    id: "hotel",
    name: "Kimpton De Witt",
    kicker: "Eure Basis · 5 Min. zum Bahnhof",
    category: "basis",
    lat: 52.37712,
    lng: 4.89464,
    address: "Nieuwezijds Voorburgwal 5, 1012 RC Amsterdam",
    hours: "Check-in ab 15:00 · Check-out bis 12:00",
    price: "Frühstück inklusive / sonst €33",
    quiet: 4,
    bestTime: "Freitagabend einchecken · Sonntag Gepäck vor Abfahrt holen",
    description: "Fester Ausgangspunkt des Wochenendes. Rezeption rund um die Uhr; Frühstück im August täglich 07:00–11:00 im Café Celia.",
    note: "Hotelgarage: max. 2,05 m, €9/Stunde, höchstens €75 je 24 Stunden; nur für Hotelgäste.",
    tags: ["Hotel", "Frühstück", "Gepäck", "Rezeption"],
    source: "https://www.ihg.com/kimptonhotels/hotels/us/en/amsterdam/amsnl/hoteldetail",
  },
  {
    id: "amsterdam-centraal",
    name: "Amsterdam Centraal",
    kicker: "Zugstart zum Dutch GP",
    category: "basis",
    lat: 52.37913,
    lng: 4.90029,
    address: "Stationsplein, 1012 AB Amsterdam",
    hours: "Sonderfahrplan 21.–23. August",
    price: "Zandvoort ab ca. €7,30 je Richtung",
    quiet: 1,
    bestTime: "Sonntag gegen 08:10 am Bahnhof sein",
    description: "Direktzüge nach Zandvoort aan Zee fahren am GP-Wochenende ungefähr alle fünf Minuten. Für die Rückfahrt ist mit Schlangen zu rechnen.",
    tags: ["Zug", "NS", "31 Min.", "sehr voll"],
    source: "https://www.ns.nl/en/featured/dutch-grand-prix-retour/well-prepared-for-the-dutch-grand-prix.html",
  },
  {
    id: "zandvoort-station",
    name: "Zandvoort aan Zee",
    kicker: "Bahnhof · ca. 15 Min. zum Circuit",
    category: "gp",
    lat: 52.37515,
    lng: 4.53245,
    address: "Stationsplein, 2042 Zandvoort",
    hours: "Späte Rückzüge · live in der NS-App prüfen",
    price: "Ticket vorab kaufen",
    quiet: 1,
    bestTime: "Nach dem Gold Deck später losgehen – dann entzerrt es sich oft",
    description: "Folgt vom Bahnhof den ausgeschilderten Laufwegen. Nach dem Rennen kann die Wartezeit am Bahnhof bis zu 60 Minuten betragen.",
    tags: ["Zug", "Fußweg", "Warteschlange"],
    source: "https://dutchgp.com/en/vervoer/train/",
  },
  {
    id: "circuit",
    name: "Circuit Zandvoort",
    kicker: "Dutch Grand Prix · Gold+",
    category: "gp",
    lat: 52.38882,
    lng: 4.54086,
    address: "Burgemeester van Alphenstraat 108, 2041 KP Zandvoort",
    hours: "Sonntag 08:00–21:00 · Rennen 15:00–17:00",
    price: "Gold+ vorhanden",
    quiet: 1,
    bestTime: "Ankunft etwa 09:15–09:45",
    description: "Gold+-Sitzplatz plus Zugang zum exklusiven Fanzone Deck ab 17:30 mit Catering und Open Bar.",
    note: "Kein Wiedereinlass. Keine Schirme, Selfiesticks oder eigenen Speisen. Leere Flasche bis 0,5 l erlaubt; Ohrschutz und Poncho einpacken.",
    tags: ["F1", "Gold+", "17:30 Deck", "kein Wiedereinlass"],
    source: "https://dutchgp.com/en/gold-plus-tickets/",
  },
  {
    id: "hortus",
    name: "Hortus Botanicus",
    kicker: "Geschützte Wege & Sitzplätze",
    category: "gruen",
    lat: 52.36694,
    lng: 4.90768,
    address: "Plantage Middenlaan 2A, 1018 DD Amsterdam",
    hours: "Täglich 10:00–17:00",
    price: "Erwachsene €14,75 · 5–17 J. €7,50",
    quiet: 5,
    bestTime: "Direkt 10:00–11:00 oder 16:00–17:00",
    description: "Kompakter botanischer Garten mit ruhigen Pfaden und geschützten Sitzmöglichkeiten. Gute, planbare Ruheinsel bei wechselhaftem Wetter.",
    note: "Gewächshäuser können warm, feucht und hell sein; mittags wird das Café lebhafter.",
    tags: ["ruhig", "Garten", "Regenoption", "Sitzplätze"],
    source: "https://www.dehortus.nl/en/plan-your-visit/",
  },
  {
    id: "oba",
    name: "OBA Oosterdok",
    kicker: "Bibliothek · kostenlos & reizarm",
    category: "ruhe",
    lat: 52.37682,
    lng: 4.90819,
    address: "Oosterdokskade 143, 1011 DL Amsterdam",
    hours: "Sa/So 10:00–20:00",
    price: "Eintritt frei",
    quiet: 5,
    bestTime: "Flexible Regen- oder Überforderungsreserve",
    description: "Sieben Etagen, viele Sitzplätze und kurze Entfernung zum Hauptbahnhof. Ein verlässlicher Rückzugsort ohne Konsumzwang.",
    note: "Café/Restaurant und Terrasse im Haus; das Gebäude erkennt das Sonnenblumen-Symbol für unsichtbare Einschränkungen an.",
    tags: ["kostenlos", "drinnen", "reizarm", "WC", "Café"],
    source: "https://www.iamsterdam.com/en/whats-on/calendar/attractions-and-sights/attractions/amsterdam-public-library-oba",
  },
  {
    id: "begijnhof",
    name: "Begijnhof",
    kicker: "Historischer stiller Innenhof",
    category: "ruhe",
    lat: 52.36994,
    lng: 4.89019,
    address: "Begijnhof 30, 1012 WT Amsterdam",
    hours: "Täglich etwa 08:00–17:00",
    price: "Eintritt frei",
    quiet: 5,
    bestTime: "Früh am Samstag",
    description: "Kleine, zentrale Ruhepause hinter einer unscheinbaren Tür. Es ist ein bewohnter Hof – leise bleiben und Privatbereiche respektieren.",
    tags: ["kostenlos", "zentral", "kurzer Stopp", "still"],
    source: "https://hetbegijnhof.nl/?lang=en",
  },
  {
    id: "amsterdamse-bos",
    name: "Amsterdamse Bos",
    kicker: "Großer Wald · viel Abstand",
    category: "gruen",
    lat: 52.32758,
    lng: 4.85472,
    address: "Bosbaanweg 5, 1182 DB Amstelveen",
    hours: "Wald frei zugänglich",
    price: "Eintritt frei",
    quiet: 5,
    bestTime: "Samstagvormittag bei trockenem Wetter",
    description: "Die großzügigste Natur- und Abstand-Option. Vom Zentrum deutlich weiter entfernt, dafür viel Raum zum Laufen, Sitzen und Durchatmen.",
    note: "Route und aktuelle Busverbindung vor Abfahrt in 9292 prüfen.",
    tags: ["Wald", "kostenlos", "viel Platz", "Bus"],
    source: "https://www.amsterdamsebos.nl/english/directions-routes/",
  },
  {
    id: "nieuwe-ooster",
    name: "De Nieuwe Ooster",
    kicker: "Arboretum & Gedenkpark",
    category: "gruen",
    lat: 52.34691,
    lng: 4.93808,
    address: "Kruislaan 126, 1097 GA Amsterdam",
    hours: "Sa/So 10:00–17:00",
    price: "Park frei",
    quiet: 5,
    bestTime: "Wenn Innenstadt und Museen zu voll sind",
    description: "Sehr ruhiger, grüner Gedenkpark mit Arboretum im Osten der Stadt. Mehr Rückzug als klassische Sehenswürdigkeit.",
    tags: ["Arboretum", "kostenlos", "sehr ruhig", "weitläufig"],
    source: "https://www.totzover.nl/english/tickets-hours/",
  },
  {
    id: "westerpark",
    name: "Westerpark",
    kicker: "Wiese & Spazierwege",
    category: "gruen",
    lat: 52.38661,
    lng: 4.87404,
    address: "Haarlemmerweg 4, 1013 RW Amsterdam",
    hours: "Frei zugänglich",
    price: "Eintritt frei",
    quiet: 4,
    bestTime: "Früh am Samstag; Veranstaltungsflächen meiden",
    description: "Zentrumsnahes Grün, gut kombinierbar mit Koffie ende Koeck. Auf den äußeren Wegen meist ruhiger als rund um die Westergas-Hallen.",
    tags: ["Amsterdam", "Haarlemmerstraat", "Park", "kostenlos", "Picknick", "Café nah"],
    source: "https://www.amsterdam.nl/en/parks/westerpark/",
  },
  {
    id: "prinseneiland",
    name: "Prinseneiland & Westelijke Eilanden",
    kicker: "Lagerhäuser, Brücken & ruhige Grachten",
    category: "sehen",
    lat: 52.38904,
    lng: 4.88534,
    address: "Prinseneiland 1, 1013 LR Amsterdam",
    hours: "Öffentlicher Außenraum · jederzeit",
    price: "Kostenlos",
    quiet: 5,
    bestTime: "Samstag 09:00–11:30",
    description: "Ein kleiner Spaziergang durch Prinseneiland, Bickerseiland und Realeneiland: historische Speicher, Hausboote, hölzerne Zugbrücken und deutlich weniger Besucher als im Grachtengürtel.",
    note: "Wohnviertel: leise bleiben und Eingänge, Stege sowie kleine Privatgärten freihalten.",
    tags: ["Amsterdam", "Haarlemmerstraat", "Sehenswürdigkeit", "kostenlos", "Architektur", "Grachten", "ruhig"],
    source: "https://gildeamsterdam.nl/en/wandeling/western-islands/",
  },
  {
    id: "marineterrein",
    name: "Marineterrein",
    kicker: "Historisches Hafengelände am Wasser",
    category: "sehen",
    lat: 52.37299,
    lng: 4.91672,
    address: "Kattenburgerstraat 5, 1018 JA Amsterdam",
    hours: "Öffentlicher Außenraum",
    price: "Kostenlos",
    quiet: 4,
    bestTime: "Vormittags oder am späten Nachmittag",
    description: "Ehemaliges Marineareal mit Uferwegen, alten Gebäuden und weitem Blick über das Oosterdok. Gut mit der OBA zu einer ruhigen Ost-Runde kombinierbar.",
    note: "Bei Sonne können Badesteg und Wasserzone lebhafter sein; in die hinteren Grün- und Uferbereiche ausweichen.",
    tags: ["Sehenswürdigkeit", "Wasser", "Architektur", "kostenlos", "Oosterdok"],
    source: "https://www.iamsterdam.com/en/whats-on/calendar/attractions-and-sights/sights/marineterrein",
  },
  {
    id: "montelbaanstoren",
    name: "Montelbaanstoren & Oudeschans",
    kicker: "Alter Wehrturm am stilleren Kanal",
    category: "sehen",
    lat: 52.37115,
    lng: 4.90644,
    address: "Oudeschans 2, 1011 KX Amsterdam",
    hours: "Außenansicht · jederzeit",
    price: "Kostenlos",
    quiet: 4,
    bestTime: "Vor 11:00 oder ab 16:00",
    description: "Fotogener Wehrturm von 1516 an der Oudeschans. Der Turm ist nicht innen zugänglich; der eigentliche Reiz ist der ruhige Wasserblick mit Hausbooten und alten Fassaden.",
    tags: ["Sehenswürdigkeit", "Turm", "Gracht", "kostenlos", "Foto"],
    source: "https://www.iamsterdam.com/en/see-and-do/attractions-and-sights/amsterdams-architectural-style",
  },
  {
    id: "groenburgwal",
    name: "Groenburgwal & Staalmeestersbrug",
    kicker: "Klassischer Blick auf die Zuiderkerk",
    category: "sehen",
    lat: 52.36822,
    lng: 4.89768,
    address: "Staalstraat 17, 1011 JK Amsterdam",
    hours: "Öffentlicher Außenraum · jederzeit",
    price: "Kostenlos",
    quiet: 4,
    bestTime: "Früh am Samstag",
    description: "Ein kurzer, autofreier Brückenstopp mit einem der schönsten Grachtblicke der Innenstadt: über die Groenburgwal direkt zum Turm der Zuiderkerk.",
    note: "Klein statt programmfüllend – ideal auf dem Weg zwischen Begijnhof, Café de Jaren und Oudeschans.",
    tags: ["Sehenswürdigkeit", "Brücke", "Gracht", "kostenlos", "kurzer Stopp"],
    source: "https://www.iamsterdam.com/en/see-and-do/attractions-and-sights/bridges-of-amsterdam",
  },
  {
    id: "magere-brug",
    name: "Magere Brug",
    kicker: "Weiße Zugbrücke über die Amstel",
    category: "sehen",
    lat: 52.36349,
    lng: 4.90233,
    address: "Magere Brug, 1018 EG Amsterdam",
    hours: "Öffentlicher Außenraum · jederzeit",
    price: "Kostenlos",
    quiet: 3,
    bestTime: "Früh morgens; abends schön, aber belebter",
    description: "Amsterdams bekannteste hölzerne Zugbrücke mit freiem Blick über die Amstel. Kein langer Aufenthalt nötig; am besten als Abschluss einer ruhigen Ostrunde.",
    tags: ["Sehenswürdigkeit", "Brücke", "Amstel", "kostenlos", "Foto"],
    source: "https://www.iamsterdam.com/en/see-and-do/nature-and-active/walking-and-cycling-routes/amstel-river-walking-route",
  },
  {
    id: "fournos",
    name: "Fournos Greek Coffee Bakery",
    kicker: "Ruhiges griechisches Frühstück nahe dem Hotel",
    category: "kaffee",
    lat: 52.37608,
    lng: 4.89292,
    address: "Nieuwezijds Voorburgwal 78M, 1012 SE Amsterdam",
    hours: "Sa/So 09:00–19:00",
    price: "€ · Kaffee €2,80–3,80 · Gebäck & Sandwiches",
    quiet: 4,
    bestTime: "Samstag 09:00–09:30",
    description: "Die beste kleine und stressarme Frühstücksoption nahe dem Kimpton: griechischer Kaffee, Bougatsa, Spanakopita, frisches Gebäck und Sandwiches in einem warmen, überschaubaren Café.",
    note: "Etwa 4–5 Minuten zu Fuß vom Hotel. Für viel Ruhe gleich zur Öffnung kommen; die aktuellen Einzelpreise für Gebäck und Sandwiches stehen nicht vollständig online.",
    tags: ["Amsterdam", "Frühstück", "Café", "griechisch", "Gebäck", "Sandwiches", "nah am Hotel", "ruhig"],
    source: "https://fournos-amsterdam.com/",
  },
  {
    id: "koffieschenkerij",
    name: "De Koffieschenkerij",
    kicker: "Sakristei, Garten & besonders viel Ruhe",
    category: "kaffee",
    lat: 52.37444,
    lng: 4.89805,
    address: "Oudekerksplein 27, 1012 GX Amsterdam",
    hours: "Täglich 09:00–18:00 · nur Walk-in",
    price: "€–€€ · Cappuccino ca. €3,90 · Kaffee + Kuchen ca. €10",
    quiet: 5,
    bestTime: "Samstag direkt um 09:00",
    description: "Das schönste und ruhigste längere Frühstück: ein kleines Café in der früheren Sakristei der Oude Kerk mit gemütlichem Innenraum und geschütztem Stadtgarten. Dazu Kaffee, Kuchen, Croissants und weitere kleine Frühstückssachen.",
    note: "Etwa 10–12 Minuten zu Fuß. Keine Reservierung; am Wochenende unbedingt früh kommen, weil der kleine Ort später trotz ruhiger Atmosphäre voll werden kann.",
    tags: ["Amsterdam", "Frühstück", "Café", "Garten", "Oude Kerk", "Kuchen", "Croissant", "sehr ruhig"],
    source: "https://www.koffieschenkerij.com/",
  },
  {
    id: "artista",
    name: "Artista · Brunch & Specialty Coffee",
    kicker: "Großes Frühstück direkt beim Hotel",
    category: "essen",
    lat: 52.37635,
    lng: 4.89479,
    address: "Nieuwezijds Kolk 12, 1012 PV Amsterdam",
    hours: "Täglich ab 08:00 · aktuelle Schlusszeit prüfen",
    price: "€–€€ · etwa €10–20 pro Person",
    quiet: 4,
    bestTime: "Samstag 08:15–08:45",
    description: "Die Wahl für ein richtiges Frühstück statt nur Kaffee und Gebäck: unter anderem Rührei auf Sauerteig, Avocado-, Lachs- und vegetarische Toasts, Joghurt mit Granola sowie Specialty Coffee.",
    note: "Nur etwa 2–3 Minuten vom Kimpton. Früh ist es angenehm; später setzt der deutlich lebhaftere Brunchbetrieb ein.",
    tags: ["Amsterdam", "Frühstück", "Brunch", "Rührei", "Avocado", "Granola", "Specialty Coffee", "nah am Hotel"],
    source: "https://artista-amsterdam.com/",
  },
  {
    id: "stadspaleis",
    name: "Het Stadspaleis",
    kicker: "Kleines Café nahe Hotel",
    category: "kaffee",
    lat: 52.37134,
    lng: 4.8892,
    address: "Nieuwezijds Voorburgwal 277, 1012 RL Amsterdam",
    hours: "Fr–So etwa 10:00–19:00",
    price: "€",
    quiet: 4,
    bestTime: "10:00–11:30 oder 15:00–17:00",
    description: "Kompaktes, freundliches Café mit Sandwiches und kleinem geschütztem Außenbereich. Praktisch für einen ruhigen Stopp nahe der Basis.",
    tags: ["Café", "Sandwiches", "nah", "klein"],
    source: "https://www.stadspaleis.com/",
  },
  {
    id: "koffie-koeck",
    name: "Koffie ende Koeck",
    kicker: "Veganes Café am Westerpark",
    category: "kaffee",
    lat: 52.38592,
    lng: 4.87301,
    address: "Haarlemmerweg 175, 1014 MA Amsterdam",
    hours: "Sa/So etwa 10:00–17:00",
    price: "€–€€",
    quiet: 4,
    bestTime: "Direkt nach Öffnung",
    description: "Sehr gemütlich, komplett vegan und direkt am Grün. Nur etwa 16 Plätze innen – falls voll, Kaffee und Kuchen mit in den Park nehmen.",
    tags: ["Amsterdam", "Haarlemmerstraat", "vegan", "Kuchen", "Park", "wenige Plätze"],
    source: "https://www.koffieendekoeck.nl/",
  },
  {
    id: "toki",
    name: "TOKI",
    kicker: "Specialty Coffee in einer ruhigen Seitenstraße",
    category: "kaffee",
    lat: 52.38402,
    lng: 4.88872,
    address: "Binnen Dommersstraat 15, 1013 HK Amsterdam",
    hours: "Sa/So 09:00–17:00",
    price: "€–€€ · Kaffee, Tee & Gebäck",
    quiet: 3,
    bestTime: "Samstag direkt um 09:00",
    description: "Kleines Specialty-Coffee-Café wenige Schritte nördlich der Haarlemmerdijk. Eine gute frühe Pause mit Kaffee, Tee und Gebäck, bevor die Einkaufsstraße voller wird.",
    note: "Beliebt und nicht groß. Für die ruhigste Chance gleich zur Öffnung kommen; wenn alle Plätze belegt sind, eignet sich der Kaffee zum Mitnehmen Richtung Prinseneiland.",
    tags: ["Amsterdam", "Haarlemmerstraat", "Café", "Specialty Coffee", "Gebäck", "früh", "klein"],
    source: "https://www.toki-times.com/",
  },
  {
    id: "small-world-catering",
    name: "Small World Catering",
    kicker: "Frische Sandwiches, Salate & Kuchen",
    category: "essen",
    lat: 52.38453,
    lng: 4.88321,
    address: "Binnen Oranjestraat 14, 1013 JA Amsterdam",
    hours: "Sa ab etwa 10:30 · So etwa 12:00–18:00 · aktuell prüfen",
    price: "€–€€ · Lunch & Take-away",
    quiet: 3,
    bestTime: "Samstag vor 12:00 oder zum Mitnehmen",
    description: "Winziges Café und Deli am westlichen Ende der Haarlemmerdijk mit frisch belegten Sandwiches, Salaten, Kuchen und vegetarischen Optionen. Praktisch für einen unkomplizierten, nicht zu teuren Lunch.",
    note: "Innen gibt es nur wenig Platz. Bei Betrieb Essen mitnehmen und in Richtung Prinseneiland oder Westerpark ausweichen.",
    tags: ["Amsterdam", "Haarlemmerstraat", "Sandwiches", "Salate", "Kuchen", "vegetarisch", "Take-away"],
    source: "https://smallworldcatering.nl/contact/",
  },
  {
    id: "febo-martelaarsgracht",
    name: "FEBO Martelaarsgracht",
    kicker: "Niederländische Snacks aus dem Automaten",
    category: "essen",
    lat: 52.37765,
    lng: 4.89503,
    address: "Nieuwendijk 50, 1012 MN Amsterdam",
    hours: "Täglich etwa 11:30–21:00 · live prüfen",
    price: "€ · Snacks und Pommes",
    quiet: 1,
    bestTime: "Vor 12:00 oder nur kurz abholen und im Hotel essen",
    description: "Sehr schneller, typisch niederländischer Imbiss mit Kroketten, Frikandel, Burgern und Pommes. Praktisch nahe Hotel und Bahnhof, aber kein ruhiger Essensstopp.",
    note: "Klein, hell und oft mit viel Kommen und Gehen. Für weniger Reize Essen mitnehmen; die ruhigere Pause ist anschließend im Hotel.",
    tags: ["Fast Food", "Pommes", "Kroketten", "Take-away", "sehr belebt"],
    source: "https://www.febo-martelaarsgracht-amsterdam.nl/contact",
  },
  {
    id: "manneken-pis-damrak",
    name: "Manneken Pis Damrak",
    kicker: "Pommesbude · viele Soßen · nur mitnehmen",
    category: "essen",
    lat: 52.37611,
    lng: 4.8971,
    address: "Damrak 41, 1012 LK Amsterdam",
    hours: "Täglich ab 10:00 · meist bis Mitternacht",
    price: "€ · Pommes etwa €4–7",
    quiet: 1,
    bestTime: "10:00–11:30 oder etwa 15:00–17:00",
    description: "Bekannte Pommesbude auf dem Damrak mit großer Soßenauswahl. Sehr zentral und schnell, aber direkt auf einer lauten, stark besuchten Route.",
    note: "Keine verlässliche ruhige Sitzpause: meist Schlange und Essen im Stehen oder Gehen. Bei Überlastung lieber die Nieuwendijk-Route verlassen und zum Hotel zurück.",
    tags: ["Pommes", "Take-away", "keine Sitzpause", "Touristenroute", "sehr belebt"],
    source: "https://mannekenpis.nl/en/locations",
  },
  {
    id: "vleminckx",
    name: "Vleminckx de Sausmeester",
    kicker: "Klassische Pommes im kleinen Seitenweg",
    category: "essen",
    lat: 52.3679,
    lng: 4.89101,
    address: "Voetboogstraat 33, 1012 XK Amsterdam",
    hours: "Sa/So 11:00–19:00",
    price: "€ · Pommes und Soßen",
    quiet: 2,
    bestTime: "Direkt ab 11:00 oder zwischen den Essenszeiten",
    description: "Traditions-Pommesbude in einer schmalen Seitenstraße nahe Spui. Ruhiger gelegen als Damrak, aber nur ein Verkaufsschalter und häufig eine sichtbare Schlange.",
    note: "Keine eigenen Sitzplätze. Außerhalb von Mittag- und Abendspitze ist die Schlange laut Betreiber am kürzesten; zum Essen einen ruhigeren Platz am Wasser suchen.",
    tags: ["Pommes", "Take-away", "Seitenstraße", "Schlange", "eher lebhaft"],
    source: "https://vleminckxdesausmeester.nl/en/",
  },
  {
    id: "burgerbar-kolksteeg",
    name: "Burger Bar Kolksteeg",
    kicker: "Burger & Pommes · sehr nah am Hotel",
    category: "essen",
    lat: 52.37618,
    lng: 4.89552,
    address: "Kolksteeg 2, 1012 PT Amsterdam",
    hours: "Täglich ab etwa 11:30 · spät geöffnet",
    price: "€–€€ · Burger meist €10–20",
    quiet: 2,
    bestTime: "Frühes Mittagessen oder Take-away vor dem Abendbetrieb",
    description: "Frisch zubereitete Burger und Pommes in direkter Nähe zur Basis. Die Filiale ist laut Betreiber die kleinste Burger-Bar-Adresse – praktisch, aber schnell eng.",
    note: "Wenige Plätze und abends lebhafte Innenstadtlage. Wenn innen voll oder laut: bestellen, mitnehmen und im Hotel in Ruhe essen.",
    tags: ["Burger", "Pommes", "Take-away", "wenige Plätze", "eher lebhaft"],
    source: "https://www.burgerbar.nl/locations/",
  },
  {
    id: "soup-en-zo",
    name: "Soup en Zo",
    kicker: "Schnell, warm & günstig",
    category: "essen",
    lat: 52.36928,
    lng: 4.90342,
    address: "Jodenbreestraat 94A, 1011 NS Amsterdam",
    hours: "Sa/So etwa 12:00–19:00",
    price: "€ · Suppe etwa €10",
    quiet: 3,
    bestTime: "12:00 oder als Take-away",
    description: "Überwiegend vegetarische Suppen, Salate und Brot. Wenige Plätze, aber eine unkomplizierte günstige Mahlzeit nahe Waterlooplein und Hortus.",
    tags: ["günstig", "vegetarisch", "Take-away", "schnell"],
    source: "https://soupenzo.nl/en/",
  },
  {
    id: "sla",
    name: "SLA Westerstraat",
    kicker: "Bowls, Salate & Pitas",
    category: "essen",
    lat: 52.37952,
    lng: 4.88377,
    address: "Westerstraat 34, 1015 MK Amsterdam",
    hours: "Täglich etwa 11:30–21:00",
    price: "€–€€ · meist €10–20",
    quiet: 4,
    bestTime: "Samstag vor 15:00 oder Take-away",
    description: "Helle, unkomplizierte Bowl-Küche mit ruhigerer Atmosphäre als viele Restaurants im Jordaan.",
    note: "Samstagabend wegen des Prinsengrachtconcerts die südliche Jordaan-Route meiden.",
    tags: ["Amsterdam", "Haarlemmerstraat", "Bowls", "vegetarisch", "Take-away", "leicht"],
    source: "https://ilovesla.com/en/",
  },
  {
    id: "pizzabakkers",
    name: "De Pizzabakkers",
    kicker: "Frühes, entspanntes Abendessen",
    category: "essen",
    lat: 52.38416,
    lng: 4.88015,
    address: "Haarlemmerdijk 128H, 1013 JH Amsterdam",
    hours: "Sa/So etwa 12:00–22:00",
    price: "€€ · Pizza ca. €15–18",
    quiet: 3,
    bestTime: "17:00–18:00",
    description: "Lockere, familienfreundliche Pizzeria in Gehweite vom Westerpark. Früh essen, bevor der Abendbetrieb anzieht.",
    tags: ["Amsterdam", "Haarlemmerstraat", "Pizza", "familienfreundlich", "früh essen"],
    source: "https://depizzabakkers.nl/",
  },
  {
    id: "kafenion",
    name: "Kafenion",
    kicker: "Kaffee & griechische Kleinigkeiten",
    category: "kaffee",
    lat: 52.37628,
    lng: 4.88125,
    address: "Bloemgracht 49, 1016 KD Amsterdam",
    hours: "Wochenende etwa 09:00–19:00",
    price: "€ · Kaffee ca. €2,25–4,25",
    quiet: 4,
    bestTime: "Samstagvormittag, nicht am Konzertabend",
    description: "Kleines, wohnliches Spezialitätencafé mit Gebäck und Brettspielen.",
    note: "Liegt nahe der Samstags-Crowdzone des Prinsengrachtconcerts; spätestens am frühen Nachmittag weiterziehen.",
    tags: ["Kaffee", "Gebäck", "Brettspiele", "klein"],
    source: "https://kafenionamsterdam.com/",
  },
  {
    id: "de-jaren",
    name: "Café de Jaren",
    kicker: "Großzügige Räume & Terrasse",
    category: "kaffee",
    lat: 52.36803,
    lng: 4.89573,
    address: "Nieuwe Doelenstraat 20, 1012 CP Amsterdam",
    hours: "Sa 10:00–23:00 · So 10:00–23:00",
    price: "€–€€",
    quiet: 3,
    bestTime: "10:00–11:00 oder am Nachmittag",
    description: "Großes Café mit Ausweichmöglichkeiten und Terrasse am Wasser. Nicht immer leise, aber weniger eng als viele kleine Innenstadtlokale.",
    tags: ["groß", "Terrasse", "Kaffee", "Regenoption"],
    source: "https://cafedejaren.nl/en/",
  },
  {
    id: "haerlemsche-vlaamse",
    name: "De Haerlemsche Vlaamse",
    kicker: "Frische Pommes · günstig & zentral",
    category: "essen",
    lat: 52.38093,
    lng: 4.63652,
    address: "Spekstraat 3, 2011 HM Haarlem",
    hours: "Sa 11:00–18:00",
    price: "€ · Pommes ab etwa €2,40",
    quiet: 2,
    bestTime: "Direkt um 11:00 oder zwischen den Essenszeiten",
    description: "Kleine, traditionelle Pommesbude mit frisch geschnittenen flämischen Pommes und großer Soßenauswahl. Eine der günstigsten unkomplizierten Pausen in der Innenstadt.",
    note: "Wenig Platz und zu Stoßzeiten Schlange. Am besten mitnehmen und im nahen Kenaupark oder an einem ruhigeren Grachtabschnitt essen.",
    tags: ["Haarlem", "Pommes", "günstig", "Take-away", "Imbiss"],
    source: "https://dehaerlemschevlaamse.nl/",
  },
  {
    id: "frietmeesters-haarlem",
    name: "Frietmeesters Haarlem",
    kicker: "Pommes, Loaded Fries & Burger",
    category: "essen",
    lat: 52.38036,
    lng: 4.63806,
    address: "Nieuwstraat 6, 2011 GH Haarlem",
    hours: "Sa etwa 12:00–20:00 · aktuell prüfen",
    price: "€–€€ · Pommes & schnelle Gerichte",
    quiet: 2,
    bestTime: "12:00 oder am Nachmittag außerhalb der Spitzen",
    description: "Frisch geschnittene Pommes, Loaded Fries, Smashburger und knuspriges Hähnchen. Gut für unterschiedliche Wünsche und eine schnelle, bezahlbare Mahlzeit.",
    note: "Eher Imbiss als Ruhepause. Bei viel Betrieb Take-away wählen und anschließend ins Grüne wechseln.",
    tags: ["Haarlem", "Pommes", "Burger", "Loaded Fries", "Take-away"],
    source: "https://www.frietmeesters.nl/",
  },
  {
    id: "native-haarlem",
    name: "Native Haarlem",
    kicker: "Spezialitätenkaffee in grüner Seitenstraße",
    category: "kaffee",
    lat: 52.38082,
    lng: 4.63125,
    address: "Breestraat 23, 2011 ZX Haarlem",
    hours: "Sa/So 09:00–17:00",
    price: "€–€€ · Kaffee, Frühstück & Lunch",
    quiet: 4,
    bestTime: "09:00–10:00 oder nach 15:30",
    description: "Wohnliches Spezialitätencafé abseits der größten Einkaufsachsen, mit Espresso, Filterkaffee, Gebäck und kleinen Frühstücks- und Lunchgerichten.",
    note: "Am Wochenende beliebt und nicht garantiert leise. Früh kommen; draußen in der Breestraat ist es meist entspannter als auf den Hauptstraßen.",
    tags: ["Haarlem", "Kaffee", "Frühstück", "Lunch", "Seitenstraße", "eher ruhig"],
    source: "https://europeancoffeetrip.com/cafe/nativehaarlem-koffie-haarlem/",
  },
  {
    id: "hofje-zonder-zorgen",
    name: "Hofje Zonder Zorgen",
    kicker: "Frühstück & Lunch am stillen Hofje",
    category: "kaffee",
    lat: 52.3773,
    lng: 4.63264,
    address: "Grote Houtstraat 142A, 2011 SV Haarlem",
    hours: "Sa etwa 08:30–17:00 · aktuell prüfen",
    price: "€€ · Frühstück, Lunch & Kuchen",
    quiet: 4,
    bestTime: "Früh oder nach 15:30",
    description: "Café mit Blick zum historischen Proveniershof, hausgemachten Kuchen sowie lokalen und biologischen Frühstücks- und Lunchgerichten.",
    note: "Der Hofblick ist ruhig, das kleine Café kann durch High-Tea-Gruppen voller werden. Außerhalb der Mittagszeit ist die Chance auf eine entspannte Pause am besten.",
    tags: ["Haarlem", "Café", "Hofje", "Kuchen", "Lunch", "eher ruhig"],
    source: "https://www.hofjezonderzorgen.nl/",
  },
  {
    id: "jetties-haarlem",
    name: "Jetties",
    kicker: "Hausgemacht, bio & nahe Bahnhof",
    category: "essen",
    lat: 52.38658,
    lng: 4.63583,
    address: "Kruisweg 57, 2011 LB Haarlem",
    hours: "Sa etwa 11:30–21:00 · aktuell prüfen",
    price: "€€ · Lunch, Burger, Kuchen & Kaffee",
    quiet: 3,
    bestTime: "11:30 oder 15:00–17:00",
    description: "Unkompliziertes Restaurant nahe dem Bahnhof mit hausgemachten, überwiegend biologischen Gerichten, vegetarischen Optionen, Kuchen und Kaffee.",
    note: "Bestellt wird an der Bar. Die Lage ist praktisch für Start oder Ende der Haarlem-Runde; mittags kann es lebhafter sein.",
    tags: ["Haarlem", "Restaurant", "bio", "vegetarisch", "Bahnhof", "Kaffee"],
    source: "https://jetties.eu/",
  },
  {
    id: "kenaupark-haarlem",
    name: "Kenaupark",
    kicker: "Grüne Pause direkt beim Bahnhof",
    category: "gruen",
    lat: 52.38661,
    lng: 4.63044,
    address: "Kenaupark, 2011 MR Haarlem",
    hours: "Öffentlicher Park · jederzeit",
    price: "Kostenlos",
    quiet: 5,
    bestTime: "Vormittag oder als Pause zwischen den Läden",
    description: "Kleiner grüner Stadtpark mit alten Bäumen, Rasen und Bänken wenige Minuten vom Bahnhof. Ideal, um Pommes oder Kaffee abseits der Einkaufsstraßen zu genießen.",
    note: "Bei Veranstaltungen oder gutem Wetter kann die zentrale Wiese belebter sein; an den Rändern finden sich meist ruhigere Plätze.",
    tags: ["Haarlem", "Park", "kostenlos", "Picknick", "Bahnhof", "sehr ruhig"],
    source: "https://www.visithaarlem.com/en/local-story/de-mooiste-picknickplekken-in-en-om-haarlem/",
  },
  {
    id: "haarlemmerhout",
    name: "Haarlemmerhout",
    kicker: "Alter Stadtwald mit viel Schatten",
    category: "gruen",
    lat: 52.37078,
    lng: 4.62891,
    address: "Hertenkamplaan, 2012 CV Haarlem",
    hours: "Frei zugänglich",
    price: "Kostenlos",
    quiet: 5,
    bestTime: "Vormittag; äußere Waldwege wählen",
    description: "Weitläufiger historischer Stadtwald südlich des Zentrums mit schattigen Wegen, Wiesen und viel Abstand. Deutlich mehr Rückzug als in einem kleinen Innenstadtpark.",
    note: "Rund um Streichelzoo und Pavillon kann es familienreicher werden. Für Ruhe auf die äußeren Wege und in den südlicheren Waldteil ausweichen.",
    tags: ["Haarlem", "Wald", "kostenlos", "viel Platz", "Schatten", "sehr ruhig"],
    source: "https://www.visithaarlem.com/en/local-story/de-mooiste-picknickplekken-in-en-om-haarlem/",
  },
  {
    id: "haarlemmer-kweektuin",
    name: "Haarlemmer Kweektuin",
    kicker: "Ökologischer Park & Garten",
    category: "gruen",
    lat: 52.39728,
    lng: 4.62482,
    address: "Kleverlaan 9, 2023 JC Haarlem",
    hours: "Sa saisonal geöffnet · aktuell prüfen",
    price: "Eintritt frei",
    quiet: 4,
    bestTime: "Früher Vormittag oder später Nachmittag",
    description: "Ökologischer Stadtpark auf ehemaligem Gärtnereigelände mit Gartenwegen, Gewächshausumgebung, Spielbereichen und Café. Gut als grüner Zwischenstopp nördlich des Zentrums.",
    note: "Bei Märkten oder Familienangeboten kann es lebhafter sein. Veranstaltungskalender vorab prüfen und die ruhigeren Gartenränder nutzen.",
    tags: ["Haarlem", "Garten", "Park", "kostenlos", "Café", "ökologisch"],
    source: "https://www.haarlemmerkweektuin.nl/contact/",
  },
  {
    id: "zipper-haarlemmerstraat",
    name: "Zipper Vintage Clothing",
    kicker: "American Vintage · Denim, Workwear & Sweater",
    category: "shoppen",
    lat: 52.38072,
    lng: 4.89315,
    address: "Haarlemmerstraat 8, 1013 ER Amsterdam",
    hours: "Sa 11:00–19:00 · So 12:00–18:00",
    price: "€€ · kuratierte Vintage-Kleidung",
    quiet: 3,
    bestTime: "Samstag direkt um 11:00",
    description: "Eine der ältesten Amsterdamer Vintage-Adressen, mit sorgfältig sortierter Kleidung aus den USA. Besonders interessant für Denim, Workwear, Sweater, Jacken und Einzelstücke verschiedener Jahrzehnte.",
    note: "Diese Filiale liegt an der Haarlemmerstraat in Amsterdam, nicht in der Stadt Haarlem. Der Laden ist kompakt und kann am Samstagnachmittag lebhaft werden.",
    tags: ["Amsterdam", "Haarlemmerstraat", "Kleidung", "Vintage", "Denim", "Workwear", "90er-Chance"],
    source: "https://zippervintageclothing.com/pages/stores",
  },
  {
    id: "kilo-store-haarlemmerstraat",
    name: "Kilo Store",
    kicker: "Vintage-Kleidung nach Gewicht",
    category: "shoppen",
    lat: 52.38218,
    lng: 4.88995,
    address: "Haarlemmerstraat 78, 1013 ET Amsterdam",
    hours: "Sa 11:00–19:00 · So 11:00–18:00",
    price: "€–€€ · Preis nach Gewicht/Farbcode",
    quiet: 2,
    bestTime: "Samstag direkt um 11:00",
    description: "Große Auswahl an authentischer Vintage-Kleidung, die überwiegend nach Gewicht und Farbcode berechnet wird. Gute Adresse für Jeans, Jacken, Sportswear und günstigere 70er- bis Y2K-Funde.",
    note: "Nur als Kleidungsstopp aufgenommen. Durch die Größe und das Kilo-Konzept wird intensiver gestöbert; am Wochenende eher lebhaft.",
    tags: ["Amsterdam", "Haarlemmerstraat", "Kleidung", "Kilo", "Vintage", "Y2K", "2000er", "günstiger"],
    source: "https://kilostore.nl/haarlemmerstraat/",
  },
  {
    id: "rumors-29",
    name: "Rumors 29",
    kicker: "Kuratierte 60er-/70er-Mode & Einzelstücke",
    category: "shoppen",
    lat: 52.38118,
    lng: 4.89215,
    address: "Haarlemmerstraat 29, 1013 EJ Amsterdam",
    hours: "Sa/So 11:00–19:00",
    price: "€€–€€€ · kuratiertes Vintage",
    quiet: 3,
    bestTime: "Samstag 11:00–12:00",
    description: "Kuratierte Vintage-Boutique mit Schwerpunkt auf 60er- und 70er-Kleidung, auffälligen Prints, Levi’s, Wildleder, Kleidern und besonderen Einzelstücken.",
    note: "Haarlemmerstraat-Filiale in Amsterdam. Gut sortiert, aber nicht auf Schnäppchenpreise ausgerichtet; für günstigere Mengenfunde zuerst Kilo Store ansehen.",
    tags: ["Amsterdam", "Haarlemmerstraat", "Kleidung", "Vintage", "60er", "70er", "Levi's", "Boutique"],
    source: "https://www.rumorsvintage.nl/en/service/about/",
  },
  {
    id: "rumors-99",
    name: "Rumors 99",
    kicker: "Große Rumors-Auswahl mit Sale-Untergeschoss",
    category: "shoppen",
    lat: 52.38272,
    lng: 4.8889,
    address: "Haarlemmerstraat 99, 1013 EM Amsterdam",
    hours: "Sa/So 11:00–19:00",
    price: "€€–€€€ · Sale-Racks möglich",
    quiet: 2,
    bestTime: "Samstag direkt um 11:00",
    description: "Zweite Rumors-Boutique mit hochwertiger Vintage-Kleidung, Leder, Schuhen und Accessoires. Im Untergeschoss gibt es regelmäßig umfangreiche Sale-Auswahl.",
    note: "Die Sale-Etage kann voller und enger sein. Für eine ruhigere Auswahl zuerst Rumors 29 besuchen und diese Filiale danach ergänzen.",
    tags: ["Amsterdam", "Haarlemmerstraat", "Kleidung", "Vintage", "60er", "70er", "Sale", "Boutique"],
    source: "https://www.rumorsvintage.nl/en/",
  },
  {
    id: "we-are-vintage-kinkerstraat",
    name: "We Are Vintage · Kinkerstraat",
    kicker: "Sportswear, 90er & Y2K für Frauen und Männer",
    category: "shoppen",
    lat: 52.3656,
    lng: 4.86672,
    address: "Kinkerstraat 193, 1053 DR Amsterdam",
    hours: "Sa/So 11:00–19:00",
    price: "€€ · kuratierte Alltags-Vintage",
    quiet: 3,
    bestTime: "Samstag 11:00–12:00",
    description: "Kleidungsfokussierter Vintage-Laden mit 70er-Streetwear, 90er-Looks, Y2K-Mode, Denim, Sportswear und Party-Kleidung für Frauen und Männer.",
    note: "Liegt westlich der kompakten Haarlemmerstraat-Runde. Besonders sinnvoll, wenn 90er- und frühe-2000er-Kleidung wichtiger ist als 60er-/70er-Boutique-Vintage.",
    tags: ["Amsterdam", "Kinkerstraat", "Kleidung", "90er", "Y2K", "2000er", "Sportswear", "Denim"],
    source: "https://www.rumorsvintage.nl/en/service/over-we-are-vintage/",
  },
  {
    id: "we-are-vintage-oost",
    name: "We Are Vintage · Oost",
    kicker: "90er-/Y2K-Kleidung in Amsterdam-Oost",
    category: "shoppen",
    lat: 52.3623,
    lng: 4.92487,
    address: "Eerste van Swindenstraat 43, 1093 EV Amsterdam",
    hours: "Sa/So 11:00–19:00",
    price: "€€ · kuratierte Alltags-Vintage",
    quiet: 3,
    bestTime: "Samstag direkt um 11:00",
    description: "Zweite We-Are-Vintage-Filiale mit Kleidung, Schuhen und Accessoires von den 70ern bis in die 2000er. Gute Auswahl an Sportswear, Streetwear, Denim und Y2K-Stücken.",
    note: "Liegt in Amsterdam-Oost und nicht auf der Haarlemmerstraat-Runde. Lässt sich sinnvoll mit OBA, Hortus oder De Nieuwe Ooster kombinieren.",
    tags: ["Amsterdam", "Oost", "Kleidung", "90er", "Y2K", "2000er", "Sportswear", "Streetwear"],
    source: "https://www.rumorsvintage.nl/en/service/over-we-are-vintage/",
  },
  {
    id: "revive-haarlem",
    name: "Revive Haarlem",
    kicker: "Designer-Vintage + 90er-/Y2K-Gast-Racks",
    category: "shoppen",
    lat: 52.3801,
    lng: 4.63291,
    address: "Gasthuisstraat 34, 2011 XP Haarlem",
    hours: "Sa 12:00–17:00 · So 13:00–17:00",
    price: "€€–€€€ · kuratiertes Vintage",
    quiet: 4,
    bestTime: "Samstag direkt um 12:00",
    description: "Kuratierter Vintage-Laden mit Designer- und bekannten Markenstücken. Im August gibt es zusätzlich wechselnde Gast-Racks mit handverlesenen 90er- und Y2K-Teilen.",
    note: "Der 90er-/Y2K-Bestand ist tagesabhängig und nicht garantiert. Für die aktuelle Auswahl zuerst hier schauen, danach Kat & Ko und NUDE als Chancenstopps.",
    tags: ["Haarlem", "Vintage", "90er", "Y2K", "2000er", "Designer", "kuratierte Mode"],
    source: "https://revivehaarlem.com/nl/pages/visit-us",
  },
  {
    id: "nude-manifesto-haarlem",
    name: "NUDE Manifesto",
    kicker: "Kuratierte Basics mit 90er-/Y2K-Chance",
    category: "shoppen",
    lat: 52.38104,
    lng: 4.63622,
    address: "Paarlaarsteeg 4, 2011 TA Haarlem",
    hours: "Samstag geöffnet · aktuelle Zeit prüfen",
    price: "€€ · kuratierte Secondhand-Mode",
    quiet: 4,
    bestTime: "Direkt nach Öffnung",
    description: "Kleine kuratierte Boutique für tragbare Vintage- und Secondhand-Basics. Gute Chance auf typische 90er- und frühe-2000er-Silhouetten, Denim und schlichte Einzelstücke.",
    note: "Nicht ausschließlich auf Y2K spezialisiert; das Sortiment wechselt. Als kurzer Chancenstopp nahe den anderen Innenstadtläden einplanen.",
    tags: ["Haarlem", "Vintage", "90er-Chance", "Y2K-Chance", "2000er", "Basics", "Boutique"],
    source: "https://www.visithaarlem.com/en/local-story/vintage-winkelen/",
  },
  {
    id: "appel-ei-haarlem",
    name: "Appel & Ei Haarlem",
    kicker: "Geräumt, ordentlich & nahe Bahnhof",
    category: "shoppen",
    lat: 52.3867526,
    lng: 4.6364177,
    address: "Kruisweg 52–54, 2011 LD Haarlem",
    hours: "Sa 10:00–18:00 · So 12:00–18:00",
    price: "€–€€ · Secondhand-Mode",
    quiet: 4,
    bestTime: "Samstag direkt ab 10:00",
    description: "Großer, übersichtlich sortierter Secondhand-Laden für Damenmode, Schuhe und Accessoires. Vom Bahnhof schnell erreichbar und durch die geräumige Aufteilung die ruhigste Startadresse der Haarlem-Runde.",
    note: "Ankauf und Sortiment wechseln laufend. Für möglichst wenig Betrieb gleich zur Öffnung kommen.",
    tags: ["Haarlem", "Secondhand", "Mode", "nah am Bahnhof", "geräumig"],
    source: "https://appelenei.nl/en/haarlem/",
  },
  {
    id: "kat-ko-haarlem",
    name: "Kat & Ko",
    kicker: "Bunt, eigenwillig & eher günstig",
    category: "shoppen",
    lat: 52.379037,
    lng: 4.6343,
    address: "Gedempte Oude Gracht 85, 2011 GN Haarlem",
    hours: "Samstag geöffnet · aktuelle Zeit prüfen",
    price: "€–€€ · faire Preise",
    quiet: 3,
    bestTime: "Direkt nach Öffnung oder am späten Nachmittag",
    description: "Farbenfroher Secondhand-Laden mit Kleidung und überraschenden Einzelstücken. Gute Adresse für bezahlbare Funde, aber kompakter und dadurch schneller lebhaft.",
    note: "Bei zu viel Betrieb lässt sich der Laden gut als kurzer Stopp zwischen Gedempte Oude Gracht und Gierstraat behandeln.",
    tags: ["Haarlem", "Secondhand", "günstiger", "bunt", "kompakt", "90er-Chance", "Y2K-Chance"],
    source: "https://www.visithaarlem.com/en/local-story/vintage-winkelen/",
  },
  {
    id: "vintage-no5-haarlem",
    name: "Vintage Nō 5",
    kicker: "Designer-Vintage in kleiner Boutique",
    category: "shoppen",
    lat: 52.378308,
    lng: 4.631317,
    address: "Gierstraat 50, 2011 GE Haarlem",
    hours: "Samstag geöffnet · aktuelle Zeit prüfen",
    price: "€€–€€€ · Designerstücke",
    quiet: 4,
    bestTime: "Vormittags oder nach 16:00",
    description: "Kleine, sorgfältig kuratierte Boutique für hochwertige Vintage- und Designer-Mode. Meist ruhiger als große Trödelläden, dafür nicht die günstigste Adresse.",
    note: "Für besondere Stücke einplanen; bei kleinem Budget eher Appel & Ei oder Kat & Ko priorisieren.",
    tags: ["Haarlem", "Vintage", "Designer", "Boutique", "hochwertig"],
    source: "https://www.visithaarlem.com/locaties/vintage-no-5/",
  },
];

export const categoryOrder: PlaceCategory[] = ["basis", "ruhe", "gruen", "sehen", "essen", "kaffee", "shoppen", "gp"];
